### ISSUE TITLE
Non blocking proxy

### ISSUE THREAD

**Issue by aleixq** [mougrim/php-xdebug-proxy#28]
As with pydgbpproxy from komodo, this also blocks all the sockets until the xdebug session has ended. If I am correct one neat solution will be use http-session amphp component, but I cannot find the documentation to carry on, did you try to be able to listen to multiple sessions in parallel or concurrent?

**Comment by aleixq** [comment]
My fault... it was a bad conf of my fpm having one pm children with static... It drives my nut for a day.... sorry It works as it should!

**Comment by mougrim** [comment]
It happens.
