### ISSUE TITLE
Timeout faster if there is no IDE

### ISSUE THREAD

**Issue by bilogic** [mougrim/php-xdebug-proxy#38]
> Amp\Socket\ConnectException: Connecting to tcp://192.168.1.3:9000 failed: timeout exceeded (10000 ms)

Is there a way to adjust the 10 seconds timeout? It causes the website to become very slow if the IDE's debugger is not running. Thank you!

**Comment by mougrim** [comment]
Hey!

Php-xdebug-proxy doesn't support timeout, but feel free, to create MR.

Need to provide from config timeout in src/Handler/DefaultIdeHandler.php:386:
```php
$ideContext = (new ClientConnectContext())
    ->withConnectTimeout($this->config->getIdeConnectTimeout());
$ideSocket = yield connect("tcp://{$ide}", $ideContext);
```

See [amp php doc](https://amphp.org/socket).

**Comment by bilogic** [comment]
Thanks for getting back!

To give this more context, my XDebugger was constantly being triggered resulting in slow loading times due to waiting for timeout.

I found out why: the XDebug helper extension for Chrome https://chrome.google.com/webstore/detail/xdebug-helper/eadndfjplgieldjbigjakmdgkmoaaaoc?hl=en dated 2016-10-24 is buggy.

It often sends the `idekey` even though its icon showed it was disabled.

Given this new info, a long timeout is actually a good thing, it points towards a bad/misconfigured tooling.
